import type { Metadata } from "next";
import { Inconsolata } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inconsolata = Inconsolata({
  subsets: ["latin"],
  weight: ["200", "400", "700", "300", "500", "600", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inconsolata.className} scrollable-container`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
